# Generated by Django 5.1 on 2024-09-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_organization_address_organization_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Organization Head', 'Organization Head'), ('Manager', 'Manager'), ('Other', 'Other')], default='Organization Head', max_length=100),
        ),
    ]
