# Generated by Django 5.1 on 2024-09-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='organizations/'),
        ),
    ]
