# Generated by Django 5.1 on 2024-09-05 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_count', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LuckyDrawSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.FileField(blank=True, null=True, upload_to='lucky_draws/')),
                ('hero_image', models.FileField(blank=True, null=True, upload_to='lucky_draws/')),
                ('main_offer_stamp_image', models.FileField(blank=True, null=True, upload_to='lucky_draws/')),
                ('qr', models.FileField(blank=True, null=True, upload_to='lucky_draws/')),
                ('type', models.CharField(choices=[('Mobile Phone Brand', 'Mobile Phone Brand'), ('Electronics Shop', 'Electronics Shop'), ('Other Shop', 'Other Shop')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IMEINO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_no', models.CharField(max_length=400, unique=True)),
                ('phone_model', models.CharField(blank=True, max_length=400)),
                ('used', models.BooleanField(default=False)),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imei_numbers', to='offers.luckydrawsystem')),
            ],
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='gift_items/')),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_items', to='offers.luckydrawsystem')),
            ],
        ),
        migrations.CreateModel(
            name='FixOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_no', models.CharField(max_length=400)),
                ('quantity', models.PositiveIntegerField()),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.giftitem')),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_offers', to='offers.luckydrawsystem')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type_of_offer', models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('Monthly Offer', 'Monthly Offer')], max_length=30)),
                ('offer_condition_value', models.CharField(blank=True, max_length=500)),
                ('sale_numbers', models.JSONField(blank=True, null=True)),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.luckydrawsystem')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='MobilePhoneOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type_of_offer', models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('Monthly Offer', 'Monthly Offer')], max_length=30)),
                ('offer_condition_value', models.CharField(blank=True, max_length=500)),
                ('sale_numbers', models.JSONField(blank=True, null=True)),
                ('per_day', models.PositiveIntegerField(default=0)),
                ('validto', models.CharField(choices=[('V Series Offer', 'V Series Offer'), ('Y Series Offer', 'Y Series Offer'), ('All', 'All')], default='All', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.giftitem')),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.luckydrawsystem')),
            ],
            options={
                'ordering': ('start_date', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='RechargeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=400, unique=True)),
                ('provider', models.CharField(choices=[('Ncell', 'Ncell'), ('Ntc', 'Ntc'), ('Smart Cell', 'Smart Cell'), ('Others', 'Others')], max_length=20)),
                ('amount', models.IntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500')])),
                ('is_assigned', models.BooleanField(default=False)),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_cards', to='offers.luckydrawsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=400)),
                ('shop_name', models.TextField()),
                ('sold_area', models.CharField(max_length=800)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_model', models.CharField(max_length=400)),
                ('sale_status', models.CharField(default='SOLD', max_length=20)),
                ('prize_details', models.CharField(default='Thank You', max_length=900)),
                ('imei', models.CharField(blank=True, max_length=400)),
                ('date_of_purchase', models.DateField(auto_now_add=True)),
                ('how_know_about_campaign', models.CharField(choices=[('Facebook Ads', 'Facebook Ads'), ('Retail Shop', 'Retail Shop'), ('Google Ads', 'Google Ads'), ('Others', 'Others')], max_length=20)),
                ('ntc_recharge_card', models.BooleanField(default=False)),
                ('amount_of_card', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('profession', models.CharField(default='None', max_length=400)),
                ('gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.giftitem')),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='offers.luckydrawsystem')),
                ('recharge_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='offers.rechargecard')),
            ],
            options={
                'ordering': ('-date_of_purchase',),
            },
        ),
        migrations.CreateModel(
            name='RechargeCardOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type_of_offer', models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position'), ('Weekly Offer', 'Weekly Offer'), ('Monthly Offer', 'Monthly Offer')], max_length=30)),
                ('offer_condition_value', models.CharField(blank=True, max_length=500)),
                ('sale_numbers', models.JSONField(blank=True, null=True)),
                ('amount', models.IntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500')], default=50)),
                ('provider', models.CharField(choices=[('Ncell', 'Ncell'), ('Ntc', 'Ntc'), ('Smart Cell', 'Smart Cell'), ('Others', 'Others')], default='Ncell', max_length=20)),
                ('lucky_draw_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.luckydrawsystem')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
