# Generated by Django 5.1 on 2024-09-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mobilephoneoffer',
            name='validto',
            field=models.ForeignKey(default='ALL', on_delete=django.db.models.deletion.CASCADE, to='offers.mobileoffertype'),
        ),
    ]
