# Generated by Django 5.1 on 2024-09-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsystem',
            name='hero_subtitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='luckydrawsystem',
            name='hero_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
