# Generated by Django 5.1 on 2024-09-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_mobileoffertype_alter_mobilephoneoffer_validto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOfferCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_condition_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeCardCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_condition_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='MobileOfferType',
            new_name='ElectronicOfferCondition',
        ),
        migrations.RenameField(
            model_name='electronicoffercondition',
            old_name='offer_type_name',
            new_name='offer_condition_name',
        ),
        migrations.RenameField(
            model_name='electronicsshopoffer',
            old_name='quantity',
            new_name='daily_quantity',
        ),
        migrations.RenameField(
            model_name='mobilephoneoffer',
            old_name='quantity',
            new_name='daily_quantity',
        ),
        migrations.RenameField(
            model_name='rechargecardoffer',
            old_name='quantity',
            new_name='daily_quantity',
        ),
        migrations.RemoveField(
            model_name='mobilephoneoffer',
            name='validto',
        ),
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='valid_condition',
            field=models.ManyToManyField(blank=True, to='offers.electronicoffercondition'),
        ),
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='valid_to',
            field=models.CharField(choices=[('All', 'All'), ('CONDITIONAL', 'CONDITIONAL')], default='All', max_length=20),
        ),
        migrations.AddField(
            model_name='luckydrawsystem',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draw_systems', to='offers.sales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='valid_to',
            field=models.CharField(choices=[('All', 'All'), ('CONDITIONAL', 'CONDITIONAL')], default='All', max_length=20),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='valid_to',
            field=models.CharField(choices=[('All', 'All'), ('CONDITIONAL', 'CONDITIONAL')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicsshopoffer',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mobilephoneoffer',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rechargecardoffer',
            name='type_of_offer',
            field=models.CharField(choices=[('After every certain sale', 'After every certain sale'), ('At certain sale position', 'At certain sale position')], max_length=30),
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='valid_condition',
            field=models.ManyToManyField(blank=True, to='offers.mobileoffercondition'),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='valid_condition',
            field=models.ManyToManyField(blank=True, to='offers.rechargecardcondition'),
        ),
    ]
