# Generated by Django 5.1 on 2024-09-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_mobileoffercondition_rechargecardcondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicsshopoffer',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='luckydrawsystem',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='mobilephoneoffer',
            name='per_day',
        ),
        migrations.RemoveField(
            model_name='mobilephoneoffer',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='rechargecardoffer',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='sales',
            name='lucky_draw_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='offers.luckydrawsystem'),
            preserve_default=False,
        ),
    ]
