# Generated by Django 5.1 on 2024-09-13 09:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_luckydrawsystem_uuid_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsystem',
            name='terms_and_conditions',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
