# Generated by Django 5.1 on 2024-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_luckydrawsystem_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
