# Generated by Django 5.1 on 2024-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_luckydrawsystem_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsystem',
            name='how_to_participate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luckydrawsystem',
            name='redeem_condition',
            field=models.TextField(blank=True),
        ),
    ]
