# Generated by Django 5.1 on 2024-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_luckydrawsystem_how_to_participate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='how_know_about_campaign',
            field=models.CharField(choices=[('Facebook Ads', 'Facebook Ads'), ('Retail Shop', 'Retail Shop'), ('Google Ads', 'Google Ads'), ('Friends Recommendation', 'Friends Recommendation'), ('Youtube', 'Youtube'), ('Others', 'Others')], max_length=50),
        ),
    ]
