# Generated by Django 5.1 on 2024-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='has_time_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='has_time_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='has_time_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
