# Generated by Django 5.1 on 2024-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_electronicsshopoffer_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='has_region_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='has_region_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='has_region_limit',
            field=models.BooleanField(default=False),
        ),
    ]
