# Generated by Django 5.1 on 2024-09-23 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_customer_amount_of_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_of_card',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
