# Generated by Django 5.1 on 2025-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_customer_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftitem',
            name='category',
            field=models.CharField(choices=[('minor', 'Minor Gift'), ('major', 'Major Gift'), ('bumper', 'Bumper Gift')], default='minor', max_length=10),
        ),
    ]
