# Generated by Django 5.1 on 2025-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_giftitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftitem',
            name='category',
            field=models.CharField(blank=True, choices=[('minor', 'Minor Gift'), ('major', 'Major Gift'), ('bumper', 'Bumper Gift')], default='minor', max_length=10, null=True),
        ),
    ]
