# Generated by Django 5.1 on 2025-09-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_alter_giftitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_model',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recharge_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='offers.rechargecard'),
        ),
    ]
