# Generated by Django 5.1 on 2025-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_alter_customer_phone_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixoffer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
