# Generated by Django 5.1 on 2025-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_fixoffer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixoffer',
            name='imei_no',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fixoffer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
