# Generated by Django 5.1 on 2025-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_alter_fixoffer_imei_no_alter_fixoffer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftitem',
            name='category',
            field=models.CharField(blank=True, choices=[('minor', 'Minor Gift'), ('major', 'Major Gift'), ('grand', 'Grand Gift')], default='minor', max_length=10, null=True),
        ),
    ]
