# Generated by Django 5.1 on 2025-09-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_alter_giftitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='electronicsshopoffer',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='fixoffer',
            name='gift',
        ),
        migrations.AddField(
            model_name='customer',
            name='gift',
            field=models.ManyToManyField(blank=True, to='offers.giftitem'),
        ),
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='gift',
            field=models.ManyToManyField(blank=True, to='offers.giftitem'),
        ),
        migrations.AddField(
            model_name='fixoffer',
            name='gift',
            field=models.ManyToManyField(blank=True, to='offers.giftitem'),
        ),
    ]
