# Generated by Django 5.1 on 2025-09-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_remove_customer_gift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill_number',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_purchased',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
