# Generated by Django 5.1 on 2026-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_customer_bill_number_customer_product_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='imeino',
            name='region',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
