# Generated by Django 5.1 on 2026-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_imeino_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsshopoffer',
            name='target_regions',
            field=models.CharField(blank=True, help_text="Comma-separated regions (e.g. 'Kathmandu, Pokhara'). Leave blank for all regions.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mobilephoneoffer',
            name='target_regions',
            field=models.CharField(blank=True, help_text="Comma-separated regions (e.g. 'Kathmandu, Pokhara'). Leave blank for all regions.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rechargecardoffer',
            name='target_regions',
            field=models.CharField(blank=True, help_text="Comma-separated regions (e.g. 'Kathmandu, Pokhara'). Leave blank for all regions.", max_length=500, null=True),
        ),
    ]
