# Generated by Django 5.1 on 2024-10-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=150)),
                ('imei', models.BigIntegerField(unique=True)),
                ('location', models.CharField(max_length=255)),
                ('rewarded', models.BooleanField(default=False)),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('device_model', models.CharField(max_length=200)),
                ('activated', models.CharField(default='Yes', max_length=300)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('partner_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-submitted_on'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='Low', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LuckyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_on', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckyno.promoparticipant')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckyno.reward')),
            ],
            options={
                'ordering': ['-won_on'],
            },
        ),
    ]
