# Generated by Django 5.1 on 2024-10-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoparticipant',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='promoparticipant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='promoparticipant',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='promoparticipant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='promoparticipant',
            name='phone_number',
        ),
    ]
